defaults: 
  - latent: full_mt1
  - obs: pp_relu
  - model: full_support

latent:
  scale: 10000

model:
  init: 'empirical-init'
  # init: 'empirical-diag-init'
  # init: 'true-init'
  # scale_init: 10000
  # true_to_flat: 'target'
  # init_mod: 0.01